// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ClockController from "./clock_controller"
application.register("clock", ClockController)

import DropdownSearchController from "./dropdown_search_controller"
application.register("dropdown-search", DropdownSearchController)

import FiltersController from "./filters_controller"
application.register("filters", FiltersController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import NavigationController from "./navigation_controller"
application.register("navigation", NavigationController)

import NestedFormController from "./nested_form_controller"
application.register("nested-form", NestedFormController)

import SidebarController from "./sidebar_controller"
application.register("sidebar", SidebarController)

import UpdateFieldsController from "./update_fields_controller"
application.register("update-fields", UpdateFieldsController)
